package entertainment.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thunder.entertainment.dao.table.ChannelModel;
import com.thunder.entertainment.dao.table.WeiTopModel;

import entertainment.dao.ChannelModelDao;
import entertainment.dao.WeiTopModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelModelDaoConfig;
    private final DaoConfig weiTopModelDaoConfig;

    private final ChannelModelDao channelModelDao;
    private final WeiTopModelDao weiTopModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelModelDaoConfig = daoConfigMap.get(ChannelModelDao.class).clone();
        channelModelDaoConfig.initIdentityScope(type);

        weiTopModelDaoConfig = daoConfigMap.get(WeiTopModelDao.class).clone();
        weiTopModelDaoConfig.initIdentityScope(type);

        channelModelDao = new ChannelModelDao(channelModelDaoConfig, this);
        weiTopModelDao = new WeiTopModelDao(weiTopModelDaoConfig, this);

        registerDao(ChannelModel.class, channelModelDao);
        registerDao(WeiTopModel.class, weiTopModelDao);
    }
    
    public void clear() {
        channelModelDaoConfig.clearIdentityScope();
        weiTopModelDaoConfig.clearIdentityScope();
    }

    public ChannelModelDao getChannelModelDao() {
        return channelModelDao;
    }

    public WeiTopModelDao getWeiTopModelDao() {
        return weiTopModelDao;
    }

}
